-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-09-02 22:30:07 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g


DROP TABLE AppUser CASCADE CONSTRAINTS 
;

DROP TABLE Begins CASCADE CONSTRAINTS 
;

DROP TABLE Category CASCADE CONSTRAINTS 
;

DROP TABLE ConsistsOf CASCADE CONSTRAINTS 
;

DROP TABLE DesignedFor CASCADE CONSTRAINTS 
;

DROP TABLE Explains CASCADE CONSTRAINTS 
;

DROP TABLE FallsUnder CASCADE CONSTRAINTS 
;

DROP TABLE Fulfills CASCADE CONSTRAINTS 
;

DROP TABLE Has CASCADE CONSTRAINTS 
;

DROP TABLE Hook CASCADE CONSTRAINTS 
;

DROP TABLE Helps CASCADE CONSTRAINTS 
;

DROP TABLE Image CASCADE CONSTRAINTS 
;

DROP TABLE Implements CASCADE CONSTRAINTS 
;

DROP TABLE IsOptional CASCADE CONSTRAINTS 
;

DROP TABLE IsTagged CASCADE CONSTRAINTS 
;

DROP TABLE Knows CASCADE CONSTRAINTS 
;

DROP TABLE Library CASCADE CONSTRAINTS 
;

DROP TABLE OperatesWith CASCADE CONSTRAINTS 
;

DROP TABLE Pattern CASCADE CONSTRAINTS 
;

DROP TABLE Project CASCADE CONSTRAINTS 
;

DROP TABLE Recommends CASCADE CONSTRAINTS 
;

DROP TABLE Represents CASCADE CONSTRAINTS 
;

DROP TABLE Request CASCADE CONSTRAINTS 
;

DROP TABLE Reviews CASCADE CONSTRAINTS 
;

DROP TABLE Suggestion CASCADE CONSTRAINTS 
;

DROP TABLE Tag CASCADE CONSTRAINTS 
;

DROP TABLE Technique CASCADE CONSTRAINTS 
;

DROP TABLE Tutorial CASCADE CONSTRAINTS 
;

DROP TABLE Uses CASCADE CONSTRAINTS 
;

DROP TABLE Utilizes CASCADE CONSTRAINTS 
;

DROP TABLE WorksWith CASCADE CONSTRAINTS 
;

DROP TABLE Yarn CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE AppUser 
    ( 
     AppUserId INTEGER  GENERATED BY DEFAULT ON NULL AS IDENTITY , 
     UserLvl   VARCHAR2 (8 BYTE) , 
     Email     VARCHAR2 (100 CHAR) , 
     "Password"  VARCHAR2 (25 CHAR) , 
     Username  VARCHAR2 (15 CHAR) , 
     ImageId   INTEGER , 
     "Role"      VARCHAR2 (8 BYTE)  NOT NULL 
    ) 
;

ALTER TABLE AppUser 
    ADD 
    CHECK (UserLvl IN ('Advanced', 'Beginner', 'Intermediate')) 
;

ALTER TABLE AppUser 
    ADD CONSTRAINT CH_INH_AppUser 
    CHECK ("Role" IN ('Admin', 'Creator', 'Regular')) 
;


ALTER TABLE AppUser 
    ADD CONSTRAINT AppUser_PK PRIMARY KEY ( AppUserId ) ;

CREATE TABLE Begins 
    ( 
     AppUserId INTEGER  NOT NULL , 
     ProjectId INTEGER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX Begins__IDX ON Begins 
    ( 
     ProjectId ASC 
    ) 
;

ALTER TABLE Begins 
    ADD CONSTRAINT Begins_PK PRIMARY KEY ( AppUserId, ProjectId ) ;

CREATE TABLE Category 
    ( 
     CategoryId   INTEGER  GENERATED BY DEFAULT ON NULL AS IDENTITY, 
     CategoryName VARCHAR2 (100 CHAR) 
    ) 
;

ALTER TABLE Category 
    ADD CONSTRAINT Category_PK PRIMARY KEY ( CategoryId ) ;

CREATE TABLE ConsistsOf 
    ( 
     Pattern_PatternId INTEGER  NOT NULL , 
     Library_LibraryId INTEGER  NOT NULL , 
     Library_AppUserId INTEGER  NOT NULL 
    ) 
;

ALTER TABLE ConsistsOf 
    ADD CONSTRAINT ConsistsOf_PK PRIMARY KEY ( Pattern_PatternId, Library_LibraryId, Library_AppUserId ) ;

CREATE TABLE DesignedFor 
    ( 
     Yarn_YarnId INTEGER  NOT NULL , 
     Hook_HookId INTEGER  NOT NULL 
    ) 
;

ALTER TABLE DesignedFor 
    ADD CONSTRAINT DesignedFor_PK PRIMARY KEY ( Yarn_YarnId, Hook_HookId ) ;

CREATE TABLE Explains 
    ( 
     Technique_TechniqueId INTEGER  NOT NULL , 
     Tutorial_TutorialId   INTEGER  NOT NULL , 
     Tutorial_CreatorId   INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Explains 
    ADD CONSTRAINT Explains_PK PRIMARY KEY ( Technique_TechniqueId, Tutorial_TutorialId, Tutorial_CreatorId ) ;

CREATE TABLE FallsUnder 
    ( 
     Category_CategoryId INTEGER  NOT NULL , 
     Pattern_PatternId   INTEGER  NOT NULL 
    ) 
;

ALTER TABLE FallsUnder 
    ADD CONSTRAINT FallsUnder_PK PRIMARY KEY ( Category_CategoryId, Pattern_PatternId ) ;

CREATE TABLE Fulfills 
    ( 
     AppUser_AppUserId       INTEGER  NOT NULL , 
     Suggestion_SuggestionId INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Fulfills 
    ADD CONSTRAINT Fulfills_PK PRIMARY KEY ( AppUser_AppUserId, Suggestion_SuggestionId ) ;

CREATE TABLE Has 
    ( 
     Image_ImageId     INTEGER  NOT NULL , 
     Pattern_PatternId INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Has 
    ADD CONSTRAINT Has_PK PRIMARY KEY ( Image_ImageId, Pattern_PatternId ) ;

CREATE TABLE Hook 
    ( 
     HookId   INTEGER  GENERATED BY DEFAULT ON NULL AS IDENTITY, 
     HookSize FLOAT
    ) 
;

ALTER TABLE Hook 
    ADD CONSTRAINT Hook_PK PRIMARY KEY ( HookId ) ;

CREATE TABLE Helps 
    ( 
     Tutorial_TutorialId INTEGER  NOT NULL , 
     Tutorial_CreatorID INTEGER  NOT NULL , 
     Pattern_PatternId   INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Helps 
    ADD CONSTRAINT Helps_PK PRIMARY KEY ( Tutorial_TutorialId, Tutorial_CreatorId, Pattern_PatternId ) ;


CREATE TABLE Image 
    ( 
     ImageId INTEGER  GENERATED BY DEFAULT ON NULL AS IDENTITY, 
     Url     VARCHAR2 (1000 CHAR) 
    ) 
;

ALTER TABLE Image 
    ADD CONSTRAINT Image_PK PRIMARY KEY ( ImageId ) ;

CREATE TABLE Implements 
    ( 
     Technique_TechniqueId INTEGER  NOT NULL , 
     Pattern_PatternId     INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Implements 
    ADD CONSTRAINT Implements_PK PRIMARY KEY ( Technique_TechniqueId, Pattern_PatternId ) ;

CREATE TABLE IsOptional 
    ( 
     Image_ImageId       INTEGER  NOT NULL , 
     Tutorial_TutorialId INTEGER  NOT NULL , 
     Tutorial_CreatorId  INTEGER  NOT NULL 
    ) 
;

ALTER TABLE IsOptional 
    ADD CONSTRAINT IsOptional_PK PRIMARY KEY ( Image_ImageId, Tutorial_TutorialId, Tutorial_CreatorId  ) ;

CREATE TABLE IsTagged 
    ( 
     Tag_TagId         INTEGER  NOT NULL , 
     Pattern_PatternId INTEGER  NOT NULL 
    ) 
;

ALTER TABLE IsTagged 
    ADD CONSTRAINT IsTagged_PK PRIMARY KEY ( Tag_TagId, Pattern_PatternId ) ;

CREATE TABLE Knows 
    ( 
     AppUser_AppUserId     INTEGER  NOT NULL , 
     Technique_TechniqueId INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Knows 
    ADD CONSTRAINT Knows_PK PRIMARY KEY ( AppUser_AppUserId, Technique_TechniqueId ) ;

CREATE TABLE Library 
    ( 
     LibraryId          INTEGER  GENERATED BY DEFAULT ON NULL AS IDENTITY, 
     LibraryName        VARCHAR2 (100 CHAR) , 
     LibraryDescription VARCHAR2 (1000 CHAR) , 
     LibraryCreateDate  DATE , 
     AppUserId          INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Library 
    ADD CONSTRAINT Library_PK PRIMARY KEY ( LibraryId, AppUserId ) ;

CREATE TABLE OperatesWith 
    ( 
     Hook_HookId         INTEGER  NOT NULL , 
     Tutorial_TutorialId INTEGER  NOT NULL , 
     Tutorial_CreatorId  INTEGER  NOT NULL 
    ) 
;

ALTER TABLE OperatesWith 
    ADD CONSTRAINT OperatesWith_PK PRIMARY KEY ( Hook_HookId, Tutorial_TutorialId, Tutorial_CreatorId  ) ;

CREATE TABLE Pattern 
    ( 
     PatternId     INTEGER  GENERATED BY DEFAULT ON NULL AS IDENTITY, 
     Title         VARCHAR2 (100 CHAR) , 
     Description   VARCHAR2 (1000 CHAR) , 
     PatternLevel  VARCHAR2 (12 BYTE) , 
     PatternDate   DATE , 
     Rating        FLOAT , 
     Instructions  VARCHAR2 (4000 CHAR) , 
     PatternStatus VARCHAR2 (8 BYTE) 
    ) 
;

ALTER TABLE Pattern 
    ADD 
    CHECK (PatternLevel IN ('Advanced', 'Beginner', 'Intermediate')) 
;

ALTER TABLE Pattern 
    ADD 
    CHECK (PatternStatus IN ('Approved', 'Pending', 'Rejected')) 
;

ALTER TABLE Pattern 
    ADD CONSTRAINT Pattern_PK PRIMARY KEY ( PatternId ) ;

CREATE TABLE Project 
    ( 
     ProjectId    INTEGER  GENERATED BY DEFAULT ON NULL AS IDENTITY, 
     Progress     FLOAT , 
     Status       VARCHAR2 (8 BYTE) , 
     DateStart    DATE , 
     DateEnd      DATE , 
     Notes        VARCHAR2 (1000 CHAR) , 
     ParentId   INTEGER , 
     ProjectTitle VARCHAR2 (100 CHAR) 
    ) 
;

ALTER TABLE Project 
    ADD 
    CHECK (Status IN ('Dropped', 'Finished', 'Ongoing')) 
;

ALTER TABLE Project 
    ADD CONSTRAINT Project_PK PRIMARY KEY ( ProjectId ) ;

CREATE TABLE Recommends 
    ( 
     Hook_HookId       INTEGER  NOT NULL , 
     Pattern_PatternId INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Recommends 
    ADD CONSTRAINT Recommends_PK PRIMARY KEY ( Hook_HookId, Pattern_PatternId ) ;

CREATE TABLE Represents 
    ( 
     Image_ImageId           INTEGER  NOT NULL , 
     Suggestion_SuggestionId INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Represents 
    ADD CONSTRAINT Represents_PK PRIMARY KEY ( Image_ImageId, Suggestion_SuggestionId ) ;

CREATE TABLE Request 
    ( 
     RequestId     INTEGER  GENERATED BY DEFAULT ON NULL AS IDENTITY, 
     RequestDate   DATE , 
     RequestStatus VARCHAR2 (8 BYTE) , 
     AdminId       INTEGER , 
     CreatorId     INTEGER  NOT NULL , 
     PatternId     INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Request 
    ADD 
    CHECK (RequestStatus IN ('Approved', 'Pending', 'Rejected')) 
;
CREATE UNIQUE INDEX Request__IDX ON Request 
    ( 
     PatternId ASC 
    ) 
;

ALTER TABLE Request 
    ADD CONSTRAINT Request_PK PRIMARY KEY ( RequestId ) ;

CREATE TABLE Reviews 
    ( 
     Utilizes_ProjectId INTEGER  NOT NULL , 
     Utilizes_PatternId INTEGER  NOT NULL , 
     Begins_AppUserId   INTEGER  NOT NULL , 
     Begins_ProjectId   INTEGER  NOT NULL , 
     ReviewText         VARCHAR2 (500 CHAR) , 
     ReviewDate         DATE , 
     ReviewRating       INTEGER 
    ) 
;

ALTER TABLE Reviews 
    ADD CONSTRAINT Reviews_PK PRIMARY KEY ( Utilizes_ProjectId, Utilizes_PatternId, Begins_AppUserId, Begins_ProjectId ) ;

CREATE TABLE Suggestion 
    ( 
     SuggestionId   INTEGER  GENERATED BY DEFAULT ON NULL AS IDENTITY, 
     SuggestionText VARCHAR2 (1000 CHAR) , 
     AppUserId      INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Suggestion 
    ADD CONSTRAINT Suggestion_PK PRIMARY KEY ( SuggestionId ) ;

CREATE TABLE Tag 
    ( 
     TagId   INTEGER  GENERATED BY DEFAULT ON NULL AS IDENTITY, 
     TagText VARCHAR2 (100 CHAR) 
    ) 
;

ALTER TABLE Tag 
    ADD CONSTRAINT Tag_PK PRIMARY KEY ( TagId ) ;

CREATE TABLE Technique 
    ( 
     TechniqueId         INTEGER  GENERATED BY DEFAULT ON NULL AS IDENTITY, 
     TechniqueName       VARCHAR2 (100 CHAR) , 
     TechniqueDifficulty VARCHAR2 (12 BYTE) 
    ) 
;

ALTER TABLE Technique 
    ADD 
    CHECK (TechniqueDifficulty IN ('Advanced', 'Beginner', 'Intermediate')) 
;

ALTER TABLE Technique 
    ADD CONSTRAINT Technique_PK PRIMARY KEY ( TechniqueId ) ;

CREATE TABLE Tutorial 
    ( 
     TutorialId    INTEGER  GENERATED BY DEFAULT ON NULL AS IDENTITY, 
     TutorialText  VARCHAR2 (4000 CHAR) , 
     VideoUrl      VARCHAR2 (1000 CHAR) , 
     Difficulty    VARCHAR2 (12 BYTE) , 
     TutorialTitle VARCHAR2 (100 CHAR) , 
     CreatorId    INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Tutorial 
    ADD 
    CHECK (Difficulty IN ('Advanced', 'Beginner', 'Intermediate')) 
;

ALTER TABLE Tutorial 
    ADD CONSTRAINT Tutorial_PK PRIMARY KEY ( TutorialId, CreatorId ) ;

CREATE TABLE Uses 
    ( 
     Yarn_YarnId       INTEGER  NOT NULL , 
     Pattern_PatternId INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Uses 
    ADD CONSTRAINT Uses_PK PRIMARY KEY ( Yarn_YarnId, Pattern_PatternId ) ;

CREATE TABLE Utilizes 
    ( 
     ProjectId INTEGER  NOT NULL , 
     PatternId INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Utilizes 
    ADD CONSTRAINT Utilizes_PK PRIMARY KEY ( ProjectId, PatternId ) ;

CREATE TABLE WorksWith 
    ( 
     Yarn_YarnId         INTEGER  NOT NULL , 
     Tutorial_TutorialId INTEGER  NOT NULL , 
     Tutorial_CreatorId INTEGER  NOT NULL 
    ) 
;

ALTER TABLE WorksWith 
    ADD CONSTRAINT WorksWith_PK PRIMARY KEY ( Yarn_YarnId, Tutorial_TutorialId, Tutorial_CreatorId ) ;

CREATE TABLE Yarn 
    ( 
     YarnId   INTEGER  GENERATED BY DEFAULT ON NULL AS IDENTITY, 
     YarnName VARCHAR2 (100 CHAR) , 
     Type     VARCHAR2 (100 CHAR) , 
     Material VARCHAR2 (100 CHAR) , 
     Weight   INTEGER , 
     MinSize  INTEGER , 
     MaxSIze  INTEGER , 
     Color    VARCHAR2 (100 CHAR) 
    ) 
;


ALTER TABLE Yarn 
    ADD CONSTRAINT Yarn_PK PRIMARY KEY ( YarnId ) ;

ALTER TABLE AppUser 
    ADD CONSTRAINT AppUser_Image_FK FOREIGN KEY 
    ( 
     ImageId
    ) 
    REFERENCES Image 
    ( 
     ImageId
    ) 
    ON DELETE SET NULL 
;

ALTER TABLE Begins 
    ADD CONSTRAINT Begins_AppUser_FK FOREIGN KEY 
    ( 
     AppUserId
    ) 
    REFERENCES AppUser 
    ( 
     AppUserId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Begins 
    ADD CONSTRAINT Begins_Project_FK FOREIGN KEY 
    ( 
     ProjectId
    ) 
    REFERENCES Project 
    ( 
     ProjectId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE ConsistsOf 
    ADD CONSTRAINT ConsistsOf_Library_FK FOREIGN KEY 
    ( 
     Library_LibraryId,
     Library_AppUserId
    ) 
    REFERENCES Library 
    ( 
     LibraryId,
     AppUserId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE ConsistsOf 
    ADD CONSTRAINT ConsistsOf_Pattern_FK FOREIGN KEY 
    ( 
     Pattern_PatternId
    ) 
    REFERENCES Pattern 
    ( 
     PatternId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE DesignedFor 
    ADD CONSTRAINT DesignedFor_Hook_FK FOREIGN KEY 
    ( 
     Hook_HookId
    ) 
    REFERENCES Hook 
    ( 
     HookId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE DesignedFor 
    ADD CONSTRAINT DesignedFor_Yarn_FK FOREIGN KEY 
    ( 
     Yarn_YarnId
    ) 
    REFERENCES Yarn 
    ( 
     YarnId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Explains 
    ADD CONSTRAINT Explains_Technique_FK FOREIGN KEY 
    ( 
     Technique_TechniqueId
    ) 
    REFERENCES Technique 
    ( 
     TechniqueId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Explains 
    ADD CONSTRAINT Explains_Tutorial_FK FOREIGN KEY 
    ( 
     Tutorial_TutorialId,
     Tutorial_CreatorId 
    ) 
    REFERENCES Tutorial 
    ( 
     TutorialId,
     CreatorId 
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE FallsUnder 
    ADD CONSTRAINT FallsUnder_Category_FK FOREIGN KEY 
    ( 
     Category_CategoryId
    ) 
    REFERENCES Category 
    ( 
     CategoryId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE FallsUnder 
    ADD CONSTRAINT FallsUnder_Pattern_FK FOREIGN KEY 
    ( 
     Pattern_PatternId
    ) 
    REFERENCES Pattern 
    ( 
     PatternId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Fulfills 
    ADD CONSTRAINT Fulfills_AppUser_FK FOREIGN KEY 
    ( 
     AppUser_AppUserId
    ) 
    REFERENCES AppUser 
    ( 
     AppUserId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Fulfills 
    ADD CONSTRAINT Fulfills_Suggestion_FK FOREIGN KEY 
    ( 
     Suggestion_SuggestionId
    ) 
    REFERENCES Suggestion 
    ( 
     SuggestionId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Has 
    ADD CONSTRAINT Has_Image_FK FOREIGN KEY 
    ( 
     Image_ImageId
    ) 
    REFERENCES Image 
    ( 
     ImageId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Has 
    ADD CONSTRAINT Has_Pattern_FK FOREIGN KEY 
    ( 
     Pattern_PatternId
    ) 
    REFERENCES Pattern 
    ( 
     PatternId
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE Helps 
    ADD CONSTRAINT Helps_Pattern_FK FOREIGN KEY 
    ( 
     Pattern_PatternId
    ) 
    REFERENCES Pattern 
    ( 
     PatternId
    ) 
;

ALTER TABLE Helps 
    ADD CONSTRAINT Helps_Tutorial_FK FOREIGN KEY 
    ( 
     Tutorial_TutorialId,
     Tutorial_CreatorId
    ) 
    REFERENCES Tutorial 
    ( 
     TutorialId,
     CreatorId
    ) 
;


ALTER TABLE Implements 
    ADD CONSTRAINT Implements_Pattern_FK FOREIGN KEY 
    ( 
     Pattern_PatternId
    ) 
    REFERENCES Pattern 
    ( 
     PatternId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Implements 
    ADD CONSTRAINT Implements_Technique_FK FOREIGN KEY 
    ( 
     Technique_TechniqueId
    ) 
    REFERENCES Technique 
    ( 
     TechniqueId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE IsOptional 
    ADD CONSTRAINT IsOptional_Image_FK FOREIGN KEY 
    ( 
     Image_ImageId
    ) 
    REFERENCES Image 
    ( 
     ImageId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE IsOptional 
    ADD CONSTRAINT IsOptional_Tutorial_FK FOREIGN KEY 
    ( 
     Tutorial_TutorialId,
     Tutorial_CreatorId 
    ) 
    REFERENCES Tutorial 
    ( 
     TutorialId,
     CreatorId 
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE IsTagged 
    ADD CONSTRAINT IsTagged_Pattern_FK FOREIGN KEY 
    ( 
     Pattern_PatternId
    ) 
    REFERENCES Pattern 
    ( 
     PatternId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE IsTagged 
    ADD CONSTRAINT IsTagged_Tag_FK FOREIGN KEY 
    ( 
     Tag_TagId
    ) 
    REFERENCES Tag 
    ( 
     TagId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Knows 
    ADD CONSTRAINT Knows_AppUser_FK FOREIGN KEY 
    ( 
     AppUser_AppUserId
    ) 
    REFERENCES AppUser 
    ( 
     AppUserId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Knows 
    ADD CONSTRAINT Knows_Technique_FK FOREIGN KEY 
    ( 
     Technique_TechniqueId
    ) 
    REFERENCES Technique 
    ( 
     TechniqueId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Library 
    ADD CONSTRAINT Library_AppUser_FK FOREIGN KEY 
    ( 
     AppUserId
    ) 
    REFERENCES AppUser 
    ( 
     AppUserId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE OperatesWith 
    ADD CONSTRAINT OperatesWith_Hook_FK FOREIGN KEY 
    ( 
     Hook_HookId
    ) 
    REFERENCES Hook 
    ( 
     HookId
    ) 
;

ALTER TABLE OperatesWith 
    ADD CONSTRAINT OperatesWith_Tutorial_FK FOREIGN KEY 
    ( 
     Tutorial_TutorialId,
     Tutorial_CreatorId 
    ) 
    REFERENCES Tutorial 
    ( 
     TutorialId,
     CreatorId 
    ) 
;

ALTER TABLE Project 
    ADD CONSTRAINT Project_Project_FK FOREIGN KEY 
    ( 
     ParentId
    ) 
    REFERENCES Project 
    ( 
     ProjectId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Recommends 
    ADD CONSTRAINT Recommends_Hook_FK FOREIGN KEY 
    ( 
     Hook_HookId
    ) 
    REFERENCES Hook 
    ( 
     HookId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Recommends 
    ADD CONSTRAINT Recommends_Pattern_FK FOREIGN KEY 
    ( 
     Pattern_PatternId
    ) 
    REFERENCES Pattern 
    ( 
     PatternId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Represents 
    ADD CONSTRAINT Represents_Image_FK FOREIGN KEY 
    ( 
     Image_ImageId
    ) 
    REFERENCES Image 
    ( 
     ImageId
    ) 
;

ALTER TABLE Represents 
    ADD CONSTRAINT Represents_Suggestion_FK FOREIGN KEY 
    ( 
     Suggestion_SuggestionId
    ) 
    REFERENCES Suggestion 
    ( 
     SuggestionId
    ) 
;

ALTER TABLE Request 
    ADD CONSTRAINT Request_AppUser_FK FOREIGN KEY 
    ( 
     AdminId
    ) 
    REFERENCES AppUser 
    ( 
     AppUserId
    ) 
    ON DELETE SET NULL 
;

ALTER TABLE Request 
    ADD CONSTRAINT Request_AppUser_FKv2 FOREIGN KEY 
    ( 
     CreatorId
    ) 
    REFERENCES AppUser 
    ( 
     AppUserId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Request 
    ADD CONSTRAINT Request_Pattern_FK FOREIGN KEY 
    ( 
     PatternId
    ) 
    REFERENCES Pattern 
    ( 
     PatternId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Reviews 
    ADD CONSTRAINT Reviews_Begins_FK FOREIGN KEY 
    ( 
     Begins_AppUserId,
     Begins_ProjectId
    ) 
    REFERENCES Begins 
    ( 
     AppUserId,
     ProjectId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Reviews 
    ADD CONSTRAINT Reviews_Utilizes_FK FOREIGN KEY 
    ( 
     Utilizes_ProjectId,
     Utilizes_PatternId
    ) 
    REFERENCES Utilizes 
    ( 
     ProjectId,
     PatternId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Suggestion 
    ADD CONSTRAINT Suggestion_AppUser_FK FOREIGN KEY 
    ( 
     AppUserId
    ) 
    REFERENCES AppUser 
    ( 
     AppUserId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Tutorial 
    ADD CONSTRAINT Tutorial_AppUser_FK FOREIGN KEY 
    ( 
     CreatorId 
    ) 
    REFERENCES AppUser 
    ( 
     AppUserId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Uses 
    ADD CONSTRAINT Uses_Pattern_FK FOREIGN KEY 
    ( 
     Pattern_PatternId
    ) 
    REFERENCES Pattern 
    ( 
     PatternId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Uses 
    ADD CONSTRAINT Uses_Yarn_FK FOREIGN KEY 
    ( 
     Yarn_YarnId
    ) 
    REFERENCES Yarn 
    ( 
     YarnId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Utilizes 
    ADD CONSTRAINT Utilizes_Pattern_FK FOREIGN KEY 
    ( 
     PatternId
    ) 
    REFERENCES Pattern 
    ( 
     PatternId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Utilizes 
    ADD CONSTRAINT Utilizes_Project_FK FOREIGN KEY 
    ( 
     ProjectId
    ) 
    REFERENCES Project 
    ( 
     ProjectId
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE WorksWith 
    ADD CONSTRAINT WorksWith_Tutorial_FK FOREIGN KEY 
    ( 
     Tutorial_TutorialId,
     Tutorial_CreatorId 
    ) 
    REFERENCES Tutorial 
    ( 
     TutorialId,
     CreatorId 
    ) 
;

ALTER TABLE WorksWith 
    ADD CONSTRAINT WorksWith_Yarn_FK FOREIGN KEY 
    ( 
     Yarn_YarnId
    ) 
    REFERENCES Yarn 
    ( 
     YarnId
    ) 
;

CREATE OR REPLACE TRIGGER FKNTM_Begins 
BEFORE UPDATE OF AppUserId, ProjectId 
ON Begins 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table Begins is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_Library 
BEFORE UPDATE OF AppUserId 
ON Library 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table Library is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTO_Project 
BEFORE UPDATE OF ParentId
ON Project 
FOR EACH ROW 
BEGIN 
 IF :old.ParentId IS NOT NULL THEN 
  raise_application_error(-20225,'Non Transferable FK constraint Project_Project_FK on table Project is violated'); 
 END IF; 
END; 
/

CREATE OR REPLACE TRIGGER FKNTO_Request 
BEFORE UPDATE OF AdminId 
ON Request 
FOR EACH ROW 
BEGIN 
 IF :old.AdminId IS NOT NULL THEN 
  raise_application_error(-20225,'Non Transferable FK constraint Request_AppUser_FK on table Request is violated'); 
 END IF; 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_Request 
BEFORE UPDATE OF CreatorId, PatternId 
ON Request 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table Request is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_Suggestion 
BEFORE UPDATE OF AppUserId 
ON Suggestion 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table Suggestion is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_Tutorial 
BEFORE UPDATE OF CreatorId 
ON Tutorial 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table Tutorial is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_Utilizes 
BEFORE UPDATE OF PatternId, ProjectId 
ON Utilizes 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table Utilizes is violated'); 
END; 
/


CREATE OR REPLACE TRIGGER FKNTM_ConsistsOf 
BEFORE UPDATE OF Pattern_PatternId, Library_LibraryId, Library_AppUserId 
ON ConsistsOf 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table ConsistsOf is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_DesignedFor 
BEFORE UPDATE OF Yarn_YarnId, Hook_HookId 
ON DesignedFor 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table DesignedFor is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_Explains 
BEFORE UPDATE OF Technique_TechniqueId, Tutorial_TutorialId, Tutorial_CreatorId 
ON Explains 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table Explains is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_FallsUnder 
BEFORE UPDATE OF Category_CategoryId, Pattern_PatternId 
ON FallsUnder 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table FallsUnder is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_Fulfills 
BEFORE UPDATE OF AppUser_AppUserId, Suggestion_SuggestionId 
ON Fulfills 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table Fulfills is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_Has 
BEFORE UPDATE OF Image_ImageId, Pattern_PatternId 
ON Has 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table Has is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_Implements 
BEFORE UPDATE OF Technique_TechniqueId, Pattern_PatternId 
ON Implements 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table Implements is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_IsOptional 
BEFORE UPDATE OF Image_ImageId, Tutorial_TutorialId, Tutorial_CreatorId 
ON IsOptional 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table IsOptional is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_IsTagged 
BEFORE UPDATE OF Tag_TagId, Pattern_PatternId 
ON IsTagged 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table IsTagged is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_Knows 
BEFORE UPDATE OF AppUser_AppUserId, Technique_TechniqueId 
ON Knows 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table Knows is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_OperatesWith 
BEFORE UPDATE OF Hook_HookId, Tutorial_TutorialId, Tutorial_CreatorId 
ON OperatesWith 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table OperatesWith is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_Recommends 
BEFORE UPDATE OF Hook_HookId, Pattern_PatternId 
ON Recommends 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table Recommends is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_Represents 
BEFORE UPDATE OF Image_ImageId, Suggestion_SuggestionId 
ON Represents 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table Represents is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_Reviews 
BEFORE UPDATE OF Utilizes_ProjectId, Utilizes_PatternId, Begins_AppUserId, Begins_ProjectId 
ON Reviews 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table Reviews is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_Uses 
BEFORE UPDATE OF Yarn_YarnId, Pattern_PatternId 
ON Uses 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table Uses is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER FKNTM_WorksWith 
BEFORE UPDATE OF Yarn_YarnId, Tutorial_TutorialId, Tutorial_CreatorId 
ON WorksWith 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table WorksWith is violated'); 
END; 
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            31
-- CREATE INDEX                             2
-- ALTER TABLE                             84
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          25
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
